#!/bin/bash

export RESOURCE_GROUP_NAME=
export RESOURCE_GROUP_LOCATION=
export MYSQL_ADMIN_USER=
export MYSQL_ADMIN_PASSWORD=
export MYSQL_REPLICATION_USER=
export MYSQL_REPLICATION_PASSWORD=
export VM_ADMIN_USERNAME=
export PUBLIC_KEY_PATH=
export VM_SERVER_PRIVATE_IP=()
export VM_MASTER_DB_PRIVATE_IP=
export VM_REPLICA_DB_PRIVATE_IP=
export VM_OBSERVABILITY_PRIVATE_IP=
export VM_NGINX_PRIVATE_IP=
export NGINX_LOAD_BALANCING_STRATEGY=
export VM_PROXYSQL_PRIVATE_IP=