#!/bin/bash

export MYSQL_ADMIN_USER=
export MYSQL_ADMIN_PASSWORD=
export MYSQL_REPLICATION_USER=
export MYSQL_REPLICATION_PASSWORD=
export VM_SERVER_IP=()
export VM_MASTER_DB_IP=
export VM_REPLICA_DB_IP=
export VM_OBSERVABILITY_IP=
export VM_NGINX_IP=
export NGINX_LOAD_BALANCING_STRATEGY=