#!/bin/sh

export RESOURCE_GROUP_NAME=
export RESOURCE_GROUP_LOCATION=
export MYSQL_ADMIN_USER=
export MYSQL_ADMIN_PASSWORD=
export READ_REPLICA_DB_COUNT=
export SPRING_APP_REPLICAS_COUNT=
export VM_ADMIN_USERNAME=
export PUBLIC_KEY_PATH=