#!/bin/sh

export AZ_RESOURCE_GROUP_NAME=
export AZ_LOCATION=
export AZ_MYSQL_ADMIN_USER=
export AZ_MYSQL_ADMIN_PASSWORD=
export AZ_SPRING_APP_REPLICAS_COUNT=
export VM_ADMIN_USERNAME=
export PUBLIC_KEY_PATH=