site_name: Test environment for IaaS and PaaS deployment models

theme:
  name: "material"

nav:
  - Home: index.md
  - Test service: ./server_app/test_service.md
  - VirtualBox: ./VirtualBox/virtualbox.md
  - IaaS: ./IaaS/iaas.md
  - PaaS: ./PaaS/paas.md
  - Requests generator: ./requests_generator/requests_generator.md
  - Observability: ./observability/observability.md
  - Resources: ./resources.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences