site_name: Test environment for IaaS and PaaS deployment models

theme:
  name: "material"

nav:
  - Home: index.md
  - Test service: ./server_app/test_service.md
  - IaaS: ./IaaS/iaas.md
  - PaaS: ./PaaS/paas.md
  - Requests generator: ./requests_generator/requests_generator.md
